### ISSUE TITLE
the .htaccess causes login conflict

### ISSUE THREAD

**Issue by ghost** [brightcove-archive/zencoder_html5-boilerplate-for-wordpress#1]
After modifying the .htaccess file as described, I was unable to login and could not access admin pages. I tried reinstalling but that did not work either. Deleting .htaccess solved problem reinstalling the file created the problem again. Hmmm?

**Comment by eddiemonge** [comment]
Are you using Apache? Are you on a shared hosting server? Could you upload the .htaccess file that is giving you issues?

**Comment by eddiemonge** [comment]
Is this issue still valid or can it be closed?

**Comment by ghost** [comment]
Sorry about that, I was on a shared hosting server but I will close this now and thank's for the earlier reply.
