### ISSUE TITLE
Featured Images

### ISSUE THREAD

**Issue by billcolumbia** [brightcove-archive/zencoder_html5-boilerplate-for-wordpress#15]
The Use as Featured Image link is broken by this theme. I can't narrow down where it is breaking it though.

The link it is breaking is in wp-admin/includes/media.php though. When I swap themes the link comes back.

**Comment by ms-studio** [comment]
It isn't actually breaking it – simply, this theme doesn't activate the Featured Image functionality.

Like for custom menus and widgets, a theme needs to actively declare those features in the functions.php file.

Adding these lines to the functions.php will activate the Featured Image link:

``` php
/* Post-Thumbnails Support
******************************/

 if ( function_exists( 'add_theme_support' ) ) {
        add_theme_support( 'post-thumbnails' );
//     set_post_thumbnail_size( 150, 150 ); // default Post Thumbnail dimensions  
    // more info: http://codex.wordpress.org/Post_Thumbnails 
 }
```

For sure, it would make sense for a boilerplate theme to include that function by default.
