### ISSUE TITLE
relative paths for URLs?

### ISSUE THREAD

**Issue by southernroutes** [brightcove-archive/zencoder_html5-boilerplate-for-wordpress#19]
I'm using the HTML5 Boilerplate for WordPress and am using JetPack so that site visitors can subscribe to new posts via email. It appears that all images in the posts are using relative URLs, not absolute paths, so they display as broken images in the emails that are sent out. For example, the source for one image in the email I just received is:

http://wp-content/uploads/2013/07/DesignCamp_Web3.jpg

The RSS feed also appears to have locally referenced images. Any idea where to modify this so that all URLs are absolute?

Thanks!

**Comment by heff** [comment]
It looks like it's using TEMPLATE_RELATIVE_URL a bunch of places. You might start digging there.
https://github.com/zencoder/html5-boilerplate-for-wordpress/blob/7fb69b1759ea133128992533999c1e7e2dfcf1ed/functions.php#L47

**Comment by southernroutes** [comment]
Yep, that might be the issue. Thanks, I'll start digging.
