### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by joshmaag** [brightcove-archive/zencoder_html5-boilerplate-for-wordpress#23]
Perhaps I'm misunderstanding the license, but the github page says the license is "The Unlicense (aka: public domain) http://unlicense.org", yet the CSS theme block in style.css says "GNU General Public License v2.0"

Is the CSS portion GPL2? Is the whole theme GPL2? Is this just a mistake?

**Comment by heff** [comment]
Just an oversight. We're not using WP anymore and are looking for a new maintainer for this if you're interested. #22
